name: 🐞 Bug Report
title: "[Bug]: <title>"
description: Create a report to help us improve
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### How to write a good bug report?

        - Respect the issue template as much as possible.
        - The title should be short and descriptive.
        - Explain the conditions which led you to report this issue and the context.
        - The context should lead to something, an idea or a problem that you’re facing.
        - Remain clear and concise.
        - Format your messages to help the reader focus on what matters and understand the structure of your message, use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown)

  - type: checkboxes
    id: terms
    attributes:
      label: Did you search for similar issues before submitting?
      options:
        - label: Yes, I've searched similar issues on [GitHub](https://github.com/aws-observability/amazon-managed-grafana-migrator/issues) and didn't find any.
          required: true

  - type: input
    attributes:
      label: Release version
      description: |
        You should **not** use `latest` as it might be unstable. Please use
        release tags `v0.x.x`. Enter release number!
      placeholder: Your version here.
    validations:
      required: true

  - type: checkboxes
    id: permissions
    attributes:
      label: Is it a permission issue?
      options:
        - label: I have a valid [AWS CLI session](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html).
          required: true
        - label: I'm using an IAM role with [the necessary permissions](../../README).
          required: true
        - label: If migrating from a Grafana server, I used an active API key with ADMIN permissions.
          required: true

  - type: textarea
    attributes:
      label: What is your environment, configuration and the example used?
      description: |
        Go version, debug output logs, expected results

        Use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown) if needed.
      placeholder: Add information here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown) if needed.
      placeholder: Add information here.
      render: shell
    validations:
      required: false
