// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws-observability/amazon-managed-grafana-migrator/internal/pkg/aws (interfaces: api)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_api.go -package=mocks github.com/aws-observability/amazon-managed-grafana-migrator/internal/pkg/aws api

package mocks

import (
	context "context"
	reflect "reflect"

	grafana "github.com/aws/aws-sdk-go-v2/service/grafana"
	gomock "go.uber.org/mock/gomock"
)

// Mockapi is a mock of api interface.
type Mockapi struct {
	ctrl     *gomock.Controller
	recorder *MockapiMockRecorder
}

// MockapiMockRecorder is the mock recorder for Mockapi.
type MockapiMockRecorder struct {
	mock *Mockapi
}

// NewMockapi creates a new mock instance.
func NewMockapi(ctrl *gomock.Controller) *Mockapi {
	mock := &Mockapi{ctrl: ctrl}
	mock.recorder = &MockapiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockapi) EXPECT() *MockapiMockRecorder {
	return m.recorder
}

// CreateWorkspaceServiceAccountToken mocks base method.
func (m *Mockapi) CreateWorkspaceServiceAccountToken(ctx context.Context, input *grafana.CreateWorkspaceServiceAccountTokenInput, optFns ...func(*grafana.Options)) (*grafana.CreateWorkspaceServiceAccountTokenOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateWorkspaceServiceAccountToken", varargs...)
	ret0, _ := ret[0].(*grafana.CreateWorkspaceServiceAccountTokenOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspaceServiceAccountToken indicates an expected call of CreateWorkspaceServiceAccountToken.
func (mr *MockapiMockRecorder) CreateWorkspaceServiceAccountToken(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspaceServiceAccountToken", reflect.TypeOf((*Mockapi)(nil).CreateWorkspaceServiceAccountToken), varargs...)
}

// DeleteWorkspaceServiceAccountToken mocks base method.
func (m *Mockapi) DeleteWorkspaceServiceAccountToken(ctx context.Context, input *grafana.DeleteWorkspaceServiceAccountTokenInput, optFns ...func(*grafana.Options)) (*grafana.DeleteWorkspaceServiceAccountTokenOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteWorkspaceServiceAccountToken", varargs...)
	ret0, _ := ret[0].(*grafana.DeleteWorkspaceServiceAccountTokenOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWorkspaceServiceAccountToken indicates an expected call of DeleteWorkspaceServiceAccountToken.
func (mr *MockapiMockRecorder) DeleteWorkspaceServiceAccountToken(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspaceServiceAccountToken", reflect.TypeOf((*Mockapi)(nil).DeleteWorkspaceServiceAccountToken), varargs...)
}

// DescribeWorkspace mocks base method.
func (m *Mockapi) DescribeWorkspace(ctx context.Context, input *grafana.DescribeWorkspaceInput, optFns ...func(*grafana.Options)) (*grafana.DescribeWorkspaceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeWorkspace", varargs...)
	ret0, _ := ret[0].(*grafana.DescribeWorkspaceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeWorkspace indicates an expected call of DescribeWorkspace.
func (mr *MockapiMockRecorder) DescribeWorkspace(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeWorkspace", reflect.TypeOf((*Mockapi)(nil).DescribeWorkspace), varargs...)
}

// ListWorkspaces mocks base method.
func (m *Mockapi) ListWorkspaces(ctx context.Context, input *grafana.ListWorkspacesInput, optFns ...func(*grafana.Options)) (*grafana.ListWorkspacesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListWorkspaces", varargs...)
	ret0, _ := ret[0].(*grafana.ListWorkspacesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkspaces indicates an expected call of ListWorkspaces.
func (mr *MockapiMockRecorder) ListWorkspaces(ctx, input any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkspaces", reflect.TypeOf((*Mockapi)(nil).ListWorkspaces), varargs...)
}
