// Code generated by MockGen. DO NOT EDIT.
// Source: aws.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	managedgrafana "github.com/aws/aws-sdk-go/service/managedgrafana"
	gomock "github.com/golang/mock/gomock"
)

// Mockapi is a mock of api interface.
type Mockapi struct {
	ctrl     *gomock.Controller
	recorder *MockapiMockRecorder
}

// MockapiMockRecorder is the mock recorder for Mockapi.
type MockapiMockRecorder struct {
	mock *Mockapi
}

// NewMockapi creates a new mock instance.
func NewMockapi(ctrl *gomock.Controller) *Mockapi {
	mock := &Mockapi{ctrl: ctrl}
	mock.recorder = &MockapiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockapi) EXPECT() *MockapiMockRecorder {
	return m.recorder
}

// CreateWorkspaceApiKey mocks base method.
func (m *Mockapi) CreateWorkspaceApiKey(input *managedgrafana.CreateWorkspaceApiKeyInput) (*managedgrafana.CreateWorkspaceApiKeyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkspaceApiKey", input)
	ret0, _ := ret[0].(*managedgrafana.CreateWorkspaceApiKeyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorkspaceApiKey indicates an expected call of CreateWorkspaceApiKey.
func (mr *MockapiMockRecorder) CreateWorkspaceApiKey(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkspaceApiKey", reflect.TypeOf((*Mockapi)(nil).CreateWorkspaceApiKey), input)
}

// DeleteWorkspaceApiKey mocks base method.
func (m *Mockapi) DeleteWorkspaceApiKey(input *managedgrafana.DeleteWorkspaceApiKeyInput) (*managedgrafana.DeleteWorkspaceApiKeyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkspaceApiKey", input)
	ret0, _ := ret[0].(*managedgrafana.DeleteWorkspaceApiKeyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWorkspaceApiKey indicates an expected call of DeleteWorkspaceApiKey.
func (mr *MockapiMockRecorder) DeleteWorkspaceApiKey(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkspaceApiKey", reflect.TypeOf((*Mockapi)(nil).DeleteWorkspaceApiKey), input)
}

// ListWorkspaces mocks base method.
func (m *Mockapi) ListWorkspaces(input *managedgrafana.ListWorkspacesInput) (*managedgrafana.ListWorkspacesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkspaces", input)
	ret0, _ := ret[0].(*managedgrafana.ListWorkspacesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkspaces indicates an expected call of ListWorkspaces.
func (mr *MockapiMockRecorder) ListWorkspaces(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkspaces", reflect.TypeOf((*Mockapi)(nil).ListWorkspaces), input)
}
