# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # pre-commit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: setup revive
  #       run: go install github.com/mgechev/revive@latest

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: setup revive
        run: go install github.com/mgechev/revive@latest

      - name: setup staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2022.1.3

      - uses: pre-commit/action@v3.0.0

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -cover
